// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htwypulgpnqikbfvywoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0d3lwdWxncG5xaWtiZnZ5d29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTE1ODcsImV4cCI6MjA3MDk4NzU4N30.olIDbnWU1LiG6Prh4wxOqfTZrg-kLzjfu_Ca6qGYBJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});